name: Merge
version: '1.0-SNAPSHOT'
main: org.desp.merge.Merge
api-version: '1.20'
depend: [MMOItems, Vault, MongoLibraryPlugin, BinggreAPI, BinggreEconomy, MMOCore, MythicLib, VelocitySocketClient]
commands:
  merge:
